# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.21

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = C:\cmake-3.21.3\bin\cmake.exe

# The command to remove a file.
RM = C:\cmake-3.21.3\bin\cmake.exe -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = C:\TI_Project\simplelink_wifi_sdk_tuya

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:\TI_Project\simplelink_wifi_sdk_tuya

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target package
package: preinstall
	@echo Run CPack packaging tool...
	C:\cmake-3.21.3\bin\cpack.exe --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package
.PHONY : package/fast

# Special rule for the target install/strip
install/strip: preinstall
	@echo Installing the project stripped...
	C:\cmake-3.21.3\bin\cmake.exe -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@echo Installing the project stripped...
	C:\cmake-3.21.3\bin\cmake.exe -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target package_source
package_source:
	@echo Run CPack packaging tool for source...
	C:\cmake-3.21.3\bin\cpack.exe --config ./CPackSourceConfig.cmake C:/TI_Project/simplelink_wifi_sdk_tuya/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source
.PHONY : package_source/fast

# Special rule for the target install/local
install/local: preinstall
	@echo Installing only the local directory...
	C:\cmake-3.21.3\bin\cmake.exe -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@echo Installing only the local directory...
	C:\cmake-3.21.3\bin\cmake.exe -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@echo Install the project...
	C:\cmake-3.21.3\bin\cmake.exe -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@echo Install the project...
	C:\cmake-3.21.3\bin\cmake.exe -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target edit_cache
edit_cache:
	@echo Running CMake cache editor...
	C:\cmake-3.21.3\bin\cmake-gui.exe -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@echo Running CMake to regenerate build system...
	C:\cmake-3.21.3\bin\cmake.exe --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@echo Available install components are: "Unspecified"
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start C:\TI_Project\simplelink_wifi_sdk_tuya\CMakeFiles C:\TI_Project\simplelink_wifi_sdk_tuya\\CMakeFiles\progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start C:\TI_Project\simplelink_wifi_sdk_tuya\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named driverlib_cc35xx

# Build rule for target.
driverlib_cc35xx: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 driverlib_cc35xx
.PHONY : driverlib_cc35xx

# fast build rule for target.
driverlib_cc35xx/fast:
	$(MAKE) $(MAKESILENT) -f source\ti\devices\cc35xx\CMakeFiles\driverlib_cc35xx.dir\build.make source/ti/devices/cc35xx/CMakeFiles/driverlib_cc35xx.dir/build
.PHONY : driverlib_cc35xx/fast

#=============================================================================
# Target rules for targets named display_cc35xx

# Build rule for target.
display_cc35xx: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 display_cc35xx
.PHONY : display_cc35xx

# fast build rule for target.
display_cc35xx/fast:
	$(MAKE) $(MAKESILENT) -f source\ti\display\CMakeFiles\display_cc35xx.dir\build.make source/ti/display/CMakeFiles/display_cc35xx.dir/build
.PHONY : display_cc35xx/fast

#=============================================================================
# Target rules for targets named drivers_cc35xx

# Build rule for target.
drivers_cc35xx: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 drivers_cc35xx
.PHONY : drivers_cc35xx

# fast build rule for target.
drivers_cc35xx/fast:
	$(MAKE) $(MAKESILENT) -f source\ti\drivers\CMakeFiles\drivers_cc35xx.dir\build.make source/ti/drivers/CMakeFiles/drivers_cc35xx.dir/build
.PHONY : drivers_cc35xx/fast

#=============================================================================
# Target rules for targets named drivers_cc35xx_log

# Build rule for target.
drivers_cc35xx_log: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 drivers_cc35xx_log
.PHONY : drivers_cc35xx_log

# fast build rule for target.
drivers_cc35xx_log/fast:
	$(MAKE) $(MAKESILENT) -f source\ti\drivers\CMakeFiles\drivers_cc35xx_log.dir\build.make source/ti/drivers/CMakeFiles/drivers_cc35xx_log.dir/build
.PHONY : drivers_cc35xx_log/fast

#=============================================================================
# Target rules for targets named secure_drivers_cc35xx_mbedtls

# Build rule for target.
secure_drivers_cc35xx_mbedtls: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 secure_drivers_cc35xx_mbedtls
.PHONY : secure_drivers_cc35xx_mbedtls

# fast build rule for target.
secure_drivers_cc35xx_mbedtls/fast:
	$(MAKE) $(MAKESILENT) -f source\ti\drivers\secure\CMakeFiles\secure_drivers_cc35xx_mbedtls.dir\build.make source/ti/drivers/secure/CMakeFiles/secure_drivers_cc35xx_mbedtls.dir/build
.PHONY : secure_drivers_cc35xx_mbedtls/fast

#=============================================================================
# Target rules for targets named secure_drivers_cc35xx

# Build rule for target.
secure_drivers_cc35xx: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 secure_drivers_cc35xx
.PHONY : secure_drivers_cc35xx

# fast build rule for target.
secure_drivers_cc35xx/fast:
	$(MAKE) $(MAKESILENT) -f source\ti\drivers\secure\CMakeFiles\secure_drivers_cc35xx.dir\build.make source/ti/drivers/secure/CMakeFiles/secure_drivers_cc35xx.dir/build
.PHONY : secure_drivers_cc35xx/fast

#=============================================================================
# Target rules for targets named log_cc35xx

# Build rule for target.
log_cc35xx: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 log_cc35xx
.PHONY : log_cc35xx

# fast build rule for target.
log_cc35xx/fast:
	$(MAKE) $(MAKESILENT) -f source\ti\log\CMakeFiles\log_cc35xx.dir\build.make source/ti/log/CMakeFiles/log_cc35xx.dir/build
.PHONY : log_cc35xx/fast

#=============================================================================
# Target rules for targets named json_m0p

# Build rule for target.
json_m0p: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 json_m0p
.PHONY : json_m0p

# fast build rule for target.
json_m0p/fast:
	$(MAKE) $(MAKESILENT) -f source\ti\utils\json\CMakeFiles\json_m0p.dir\build.make source/ti/utils/json/CMakeFiles/json_m0p.dir/build
.PHONY : json_m0p/fast

#=============================================================================
# Target rules for targets named json_m3

# Build rule for target.
json_m3: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 json_m3
.PHONY : json_m3

# fast build rule for target.
json_m3/fast:
	$(MAKE) $(MAKESILENT) -f source\ti\utils\json\CMakeFiles\json_m3.dir\build.make source/ti/utils/json/CMakeFiles/json_m3.dir/build
.PHONY : json_m3/fast

#=============================================================================
# Target rules for targets named json_m33f

# Build rule for target.
json_m33f: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 json_m33f
.PHONY : json_m33f

# fast build rule for target.
json_m33f/fast:
	$(MAKE) $(MAKESILENT) -f source\ti\utils\json\CMakeFiles\json_m33f.dir\build.make source/ti/utils/json/CMakeFiles/json_m33f.dir/build
.PHONY : json_m33f/fast

#=============================================================================
# Target rules for targets named json_m4

# Build rule for target.
json_m4: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 json_m4
.PHONY : json_m4

# fast build rule for target.
json_m4/fast:
	$(MAKE) $(MAKESILENT) -f source\ti\utils\json\CMakeFiles\json_m4.dir\build.make source/ti/utils/json/CMakeFiles/json_m4.dir/build
.PHONY : json_m4/fast

#=============================================================================
# Target rules for targets named json_m4f

# Build rule for target.
json_m4f: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 json_m4f
.PHONY : json_m4f

# fast build rule for target.
json_m4f/fast:
	$(MAKE) $(MAKESILENT) -f source\ti\utils\json\CMakeFiles\json_m4f.dir\build.make source/ti/utils/json/CMakeFiles/json_m4f.dir/build
.PHONY : json_m4f/fast

#=============================================================================
# Target rules for targets named fatfs_m33f

# Build rule for target.
fatfs_m33f: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 fatfs_m33f
.PHONY : fatfs_m33f

# fast build rule for target.
fatfs_m33f/fast:
	$(MAKE) $(MAKESILENT) -f source\third_party\fatfs\CMakeFiles\fatfs_m33f.dir\build.make source/third_party/fatfs/CMakeFiles/fatfs_m33f.dir/build
.PHONY : fatfs_m33f/fast

#=============================================================================
# Target rules for targets named spiffs_m33f

# Build rule for target.
spiffs_m33f: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 spiffs_m33f
.PHONY : spiffs_m33f

# fast build rule for target.
spiffs_m33f/fast:
	$(MAKE) $(MAKESILENT) -f source\third_party\spiffs\CMakeFiles\spiffs_m33f.dir\build.make source/third_party/spiffs/CMakeFiles/spiffs_m33f.dir/build
.PHONY : spiffs_m33f/fast

#=============================================================================
# Target rules for targets named spiffs_m33f_cc26xx

# Build rule for target.
spiffs_m33f_cc26xx: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 spiffs_m33f_cc26xx
.PHONY : spiffs_m33f_cc26xx

# fast build rule for target.
spiffs_m33f_cc26xx/fast:
	$(MAKE) $(MAKESILENT) -f source\third_party\spiffs\CMakeFiles\spiffs_m33f_cc26xx.dir\build.make source/third_party/spiffs/CMakeFiles/spiffs_m33f_cc26xx.dir/build
.PHONY : spiffs_m33f_cc26xx/fast

#=============================================================================
# Target rules for targets named hsmddk_cc35xx

# Build rule for target.
hsmddk_cc35xx: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 hsmddk_cc35xx
.PHONY : hsmddk_cc35xx

# fast build rule for target.
hsmddk_cc35xx/fast:
	$(MAKE) $(MAKESILENT) -f source\third_party\hsmddk\CMakeFiles\hsmddk_cc35xx.dir\build.make source/third_party/hsmddk/CMakeFiles/hsmddk_cc35xx.dir/build
.PHONY : hsmddk_cc35xx/fast

#=============================================================================
# Target rules for targets named hsmddk_cc35xx_its

# Build rule for target.
hsmddk_cc35xx_its: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 hsmddk_cc35xx_its
.PHONY : hsmddk_cc35xx_its

# fast build rule for target.
hsmddk_cc35xx_its/fast:
	$(MAKE) $(MAKESILENT) -f source\third_party\hsmddk\CMakeFiles\hsmddk_cc35xx_its.dir\build.make source/third_party/hsmddk/CMakeFiles/hsmddk_cc35xx_its.dir/build
.PHONY : hsmddk_cc35xx_its/fast

#=============================================================================
# Target rules for targets named lwip

# Build rule for target.
lwip: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 lwip
.PHONY : lwip

# fast build rule for target.
lwip/fast:
	$(MAKE) $(MAKESILENT) -f source\third_party\lwip\CMakeFiles\lwip.dir\build.make source/third_party/lwip/CMakeFiles/lwip.dir/build
.PHONY : lwip/fast

#=============================================================================
# Target rules for targets named hostap

# Build rule for target.
hostap: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 hostap
.PHONY : hostap

# fast build rule for target.
hostap/fast:
	$(MAKE) $(MAKESILENT) -f source\third_party\hostap\CMakeFiles\hostap.dir\build.make source/third_party/hostap/CMakeFiles/hostap.dir/build
.PHONY : hostap/fast

#=============================================================================
# Target rules for targets named nimble

# Build rule for target.
nimble: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 nimble
.PHONY : nimble

# fast build rule for target.
nimble/fast:
	$(MAKE) $(MAKESILENT) -f source\third_party\nimble\CMakeFiles\nimble.dir\build.make source/third_party/nimble/CMakeFiles/nimble.dir/build
.PHONY : nimble/fast

#=============================================================================
# Target rules for targets named tuya

# Build rule for target.
tuya: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 tuya
.PHONY : tuya

# fast build rule for target.
tuya/fast:
	$(MAKE) $(MAKESILENT) -f source\third_party\tuya\CMakeFiles\tuya.dir\build.make source/third_party/tuya/CMakeFiles/tuya.dir/build
.PHONY : tuya/fast

#=============================================================================
# Target rules for targets named libcjson

# Build rule for target.
libcjson: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 libcjson
.PHONY : libcjson

# fast build rule for target.
libcjson/fast:
	$(MAKE) $(MAKESILENT) -f source\third_party\tuya\tuya_src\libcjson\CMakeFiles\libcjson.dir\build.make source/third_party/tuya/tuya_src/libcjson/CMakeFiles/libcjson.dir/build
.PHONY : libcjson/fast

#=============================================================================
# Target rules for targets named libhttp

# Build rule for target.
libhttp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 libhttp
.PHONY : libhttp

# fast build rule for target.
libhttp/fast:
	$(MAKE) $(MAKESILENT) -f source\third_party\tuya\tuya_src\libhttp\CMakeFiles\libhttp.dir\build.make source/third_party/tuya/tuya_src/libhttp/CMakeFiles/libhttp.dir/build
.PHONY : libhttp/fast

#=============================================================================
# Target rules for targets named libmqtt

# Build rule for target.
libmqtt: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 libmqtt
.PHONY : libmqtt

# fast build rule for target.
libmqtt/fast:
	$(MAKE) $(MAKESILENT) -f source\third_party\tuya\tuya_src\libmqtt\CMakeFiles\libmqtt.dir\build.make source/third_party/tuya/tuya_src/libmqtt/CMakeFiles/libmqtt.dir/build
.PHONY : libmqtt/fast

#=============================================================================
# Target rules for targets named tal_kv

# Build rule for target.
tal_kv: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 tal_kv
.PHONY : tal_kv

# fast build rule for target.
tal_kv/fast:
	$(MAKE) $(MAKESILENT) -f source\third_party\tuya\tuya_src\tal_kv\CMakeFiles\tal_kv.dir\build.make source/third_party/tuya/tuya_src/tal_kv/CMakeFiles/tal_kv.dir/build
.PHONY : tal_kv/fast

#=============================================================================
# Target rules for targets named tal_network

# Build rule for target.
tal_network: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 tal_network
.PHONY : tal_network

# fast build rule for target.
tal_network/fast:
	$(MAKE) $(MAKESILENT) -f source\third_party\tuya\tuya_src\tal_network\CMakeFiles\tal_network.dir\build.make source/third_party/tuya/tuya_src/tal_network/CMakeFiles/tal_network.dir/build
.PHONY : tal_network/fast

#=============================================================================
# Target rules for targets named tuya_cloud_service

# Build rule for target.
tuya_cloud_service: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 tuya_cloud_service
.PHONY : tuya_cloud_service

# fast build rule for target.
tuya_cloud_service/fast:
	$(MAKE) $(MAKESILENT) -f source\third_party\tuya\tuya_src\tuya_cloud_service\CMakeFiles\tuya_cloud_service.dir\build.make source/third_party/tuya/tuya_src/tuya_cloud_service/CMakeFiles/tuya_cloud_service.dir/build
.PHONY : tuya_cloud_service/fast

#=============================================================================
# Target rules for targets named ble_interface

# Build rule for target.
ble_interface: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 ble_interface
.PHONY : ble_interface

# fast build rule for target.
ble_interface/fast:
	$(MAKE) $(MAKESILENT) -f source\ti\net\ble_interface\CMakeFiles\ble_interface.dir\build.make source/ti/net/ble_interface/CMakeFiles/ble_interface.dir/build
.PHONY : ble_interface/fast

#=============================================================================
# Target rules for targets named wifi_stack

# Build rule for target.
wifi_stack: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 wifi_stack
.PHONY : wifi_stack

# fast build rule for target.
wifi_stack/fast:
	$(MAKE) $(MAKESILENT) -f source\ti\net\wifi_stack\CMakeFiles\wifi_stack.dir\build.make source/ti/net/wifi_stack/CMakeFiles/wifi_stack.dir/build
.PHONY : wifi_stack/fast

#=============================================================================
# Target rules for targets named wifi_host_driver

# Build rule for target.
wifi_host_driver: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 wifi_host_driver
.PHONY : wifi_host_driver

# fast build rule for target.
wifi_host_driver/fast:
	$(MAKE) $(MAKESILENT) -f source\ti\drivers\net\wifi\wifi_host_driver\CMakeFiles\wifi_host_driver.dir\build.make source/ti/drivers/net/wifi/wifi_host_driver/CMakeFiles/wifi_host_driver.dir/build
.PHONY : wifi_host_driver/fast

#=============================================================================
# Target rules for targets named wifi_platform_cc35xx

# Build rule for target.
wifi_platform_cc35xx: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 wifi_platform_cc35xx
.PHONY : wifi_platform_cc35xx

# fast build rule for target.
wifi_platform_cc35xx/fast:
	$(MAKE) $(MAKESILENT) -f source\ti\drivers\net\wifi\wifi_platform\cc35xx\CMakeFiles\wifi_platform_cc35xx.dir\build.make source/ti/drivers/net/wifi/wifi_platform/cc35xx/CMakeFiles/wifi_platform_cc35xx.dir/build
.PHONY : wifi_platform_cc35xx/fast

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... install
	@echo ... install/local
	@echo ... install/strip
	@echo ... list_install_components
	@echo ... package
	@echo ... package_source
	@echo ... rebuild_cache
	@echo ... ble_interface
	@echo ... display_cc35xx
	@echo ... driverlib_cc35xx
	@echo ... drivers_cc35xx
	@echo ... drivers_cc35xx_log
	@echo ... fatfs_m33f
	@echo ... hostap
	@echo ... hsmddk_cc35xx
	@echo ... hsmddk_cc35xx_its
	@echo ... json_m0p
	@echo ... json_m3
	@echo ... json_m33f
	@echo ... json_m4
	@echo ... json_m4f
	@echo ... libcjson
	@echo ... libhttp
	@echo ... libmqtt
	@echo ... log_cc35xx
	@echo ... lwip
	@echo ... nimble
	@echo ... secure_drivers_cc35xx
	@echo ... secure_drivers_cc35xx_mbedtls
	@echo ... spiffs_m33f
	@echo ... spiffs_m33f_cc26xx
	@echo ... tal_kv
	@echo ... tal_network
	@echo ... tuya
	@echo ... tuya_cloud_service
	@echo ... wifi_host_driver
	@echo ... wifi_platform_cc35xx
	@echo ... wifi_stack
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

